"""Persist and export War Room AI Intelligence Briefs.

Briefs are generated by Claude — the ``/trade-brief`` Claude Code skill or the
in-app prompt — and persisted to the ``war_room_briefs`` DuckDB table, the same
source of truth that feeds every other War Room number. ``save_brief`` also
writes the JSON to ``frontend/public/brief-inbox/<TEAM>.json``, which the running
app polls and renders live (Vite serves ``public/`` during ``npm run dev``).

This keeps the brief inside the established DuckDB → JSON → frontend pipeline
rather than as an ad-hoc artifact.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, date, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from savage_trade_evaluator.storage.db import connect

if TYPE_CHECKING:
    import duckdb

logger = logging.getLogger(__name__)

#: Inbox the War Room frontend polls (served at /brief-inbox/<TEAM>.json in dev).
INBOX_DIR = Path(__file__).resolve().parents[3] / "frontend" / "public" / "brief-inbox"

_DDL = """
CREATE TABLE IF NOT EXISTS war_room_briefs (
    team VARCHAR NOT NULL,
    as_of DATE NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    model VARCHAR,
    source VARCHAR,
    brief_json JSON NOT NULL,
    PRIMARY KEY (team, as_of)
)
"""


def _ensure_table(conn: duckdb.DuckDBPyConnection) -> None:
    """Create the briefs table if it does not exist (idempotent)."""
    conn.execute(_DDL)


def _write_inbox(team: str, brief_text: str) -> Path:
    """Write the brief JSON to the frontend inbox and return the path."""
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    out = INBOX_DIR / f"{team}.json"
    out.write_text(brief_text)
    return out


def _as_text(value: Any) -> str:
    """Normalize a DuckDB JSON column value to a JSON string."""
    return value if isinstance(value, str) else json.dumps(value, separators=(",", ":"))


def save_brief(
    team: str,
    brief: dict[str, Any],
    *,
    model: str | None = None,
    source: str = "skill",
    as_of: date | None = None,
    db_path: Path | None = None,
) -> Path:
    """Upsert a brief into DuckDB and write the frontend inbox file.

    Args:
        team: Baseball-Reference team code (case-insensitive).
        brief: The AnalysisReport dict produced by Claude.
        model: Optional identifier of the model that generated the brief.
        source: Origin tag — ``skill``, ``app``, or ``manual``.
        as_of: Brief date; defaults to today (UTC).
        db_path: Optional DuckDB path override (mainly for tests).

    Returns:
        The path of the written inbox file.
    """
    code = team.upper()
    when = as_of or datetime.now(UTC).date()
    payload = {**brief, "team": code}
    brief_text = json.dumps(payload, separators=(",", ":"))
    with connect(path=db_path) as conn:
        _ensure_table(conn)
        conn.execute("DELETE FROM war_room_briefs WHERE team = ? AND as_of = ?", [code, when])
        conn.execute(
            "INSERT INTO war_room_briefs "
            "(team, as_of, generated_at, model, source, brief_json) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            [code, when, datetime.now(UTC), model, source, brief_text],
        )
    out = _write_inbox(code, brief_text)
    logger.info("saved brief team=%s as_of=%s source=%s -> %s", code, when, source, out)
    return out


def export_brief(team: str, *, db_path: Path | None = None) -> bool:
    """Write the latest stored brief for a team to the frontend inbox.

    Args:
        team: Baseball-Reference team code (case-insensitive).
        db_path: Optional DuckDB path override.

    Returns:
        True if a stored brief existed and was written, else False.
    """
    code = team.upper()
    with connect(path=db_path) as conn:
        _ensure_table(conn)
        row = conn.execute(
            "SELECT brief_json FROM war_room_briefs WHERE team = ? "
            "ORDER BY as_of DESC, generated_at DESC LIMIT 1",
            [code],
        ).fetchone()
    if row is None:
        logger.warning("no stored brief for team=%s", code)
        return False
    _write_inbox(code, _as_text(row[0]))
    return True


def export_all(*, db_path: Path | None = None) -> int:
    """Write the latest brief for every team to the frontend inbox.

    Args:
        db_path: Optional DuckDB path override.

    Returns:
        The number of briefs written.
    """
    with connect(path=db_path) as conn:
        _ensure_table(conn)
        rows = conn.execute(
            "SELECT b.team, b.brief_json FROM war_room_briefs b "
            "WHERE b.generated_at = ("
            "  SELECT MAX(x.generated_at) FROM war_room_briefs x WHERE x.team = b.team"
            ")"
        ).fetchall()
    for code, value in rows:
        _write_inbox(str(code), _as_text(value))
    return len(rows)
